baseURL: https://aqlife.netlify.app/
title: 阿Q Life - Going forwrad, towards your destination
enableRobotsTXT: yes
enableEmoji: yes
theme: hugo-theme-jane
hasCJKLanguage: yes
paginate: 10
rssLimit: 20
disqusShortname: ''
googleAnalytics: ''
copyright: '阿Q Life'

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences: yes # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses: yes # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax: yes
PygmentsOptions: "linenos=table"

defaultContentLanguage: zh-cn
languages:
  zh-cn:
    languageCode: zh-cn
author:
  name: 阿Q
  url: /about
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
menu:
  main:
    - identifier: home
      name: Home
      pageref: /
      weight: 10
    - identifier: archives
      name: Archives
      pageref: /post/
      weight: 20
    - identifier: tags
      name: Tags
      pageref: /tags/
      weight: 30
    - identifier: categories
      name: Categories
      pageref: /categories/
      weight: 40
    - name: Reference
      pageref: /reference
      weight: 50
params:
  contentCopyright: <a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/"
    target="_blank">CC BY-NC-ND 4.0</a>
  customCSS: []
  customJS: []
  dateFormatToUse: '2006-01-02'
  description: Going forwrad, towards your destination
  homeFullContent: no
  keywords:
    - Hugo
    - theme
    - jane
  logoTitle: 阿Q
  archive-paginate: 50
  moreMeta: yes
  photoswipe: yes
  rssFullContent: yes
  since: '2017'
  gitment:
    owner: ''
    repo: ''
    clientId: ''
    clientSecret: ''
  social:
    a-email: qi_luo2020@163.com
    g-github: https://github.com/AQ-Life/AQ_Life
    k-pocket: https://aqlife.netlify.app/
  toc: yes
  
